[shell]
polkit_agent = true

[shell.screenshot]
save_to_file = false

[bar.default]
center = ["clock", "media"]
end = [
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session",
]
layer = "overlay"
padding = 0
reserve_space = false
smart_auto_hide = true

[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 60.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 300.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    locked_timeout = 30.0
    timeout = 60.0

[location]
address = "Chennai, India"
auto_locate = true

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
pure_black_dark = true
source = "builtin"
wallpaper_scheme = "m3-content"

[widget.bluetooth]
enabled = false

[widget.wallpaper]
enabled = false
